### ISSUE TITLE
Many, many errors 

### ISSUE THREAD

**Issue by Az-Neter** [ADM228/ATtiny85APU#1]
This repository is an absolute mess.  

The file structure is incorrect, with tn85def.inc being located in the wrong place relative to the make file.  

The readme shows incorrect information, such as listing GND multiple times on the AVR's pinout, listing incorrect conventions for pin names, and with dead links that loop back to the repository.

I'm going to pray to Fortuna that this compiled firmware doesn't light my AVR on fire, with the added hope it actually takes klystracks 10 bit pwm input.

**Comment by ADM228** [comment]
> tn85def.inc being located in the wrong place
Please show a specific example of it not working / breaking
> listing GND multiple times
This is legit my mistake, one of them is supposed to be VCC
> dead links that loop back to the repository
Intentionally done to show the repo around

> That this compiled firmware doesn't light my AVR on fire
as long as it compiled alright it *shouldn't*; do note to specifically set the clock speed to 8MHz in the fuse

**Comment by Az-Neter** [comment]
![Screenshot_20240531-223807.png](https://github.com/ADM228/ATtiny85APU/assets/119499525/4b8b1288-ca3f-46b2-876f-8046deae2a77)

**Comment by Az-Neter** [comment]
If you move the tndef file up one folder it compiles file.

**Comment by ADM228** [comment]
Added the `avr` directory as an include path in commit 6b851b1, please test if it works now

**Comment by Az-Neter** [comment]
Sorry for the late reply but I managed to get it to compile fine.
Thanks for the fix!

I have more questions though: should the fuse bits be changed for this firmware? There is no info about whether clock dividing or other fuse flags should be set. I'm confused which settings I should use for flashing tiny85.
Should they stay default?

**Comment by ADM228** [comment]
Glad it worked! I apologize for not including the fuse info, so here it is:
The only change to fuse bits needed is to disable `CKDIV8` so that the device runs at a full 8MHz. The rest should stay at their defaults.

**Comment by Az-Neter** [comment]
![PXL_20240602_031621454.jpg](https://github.com/ADM228/ATtiny85APU/assets/119499525/848c3397-9290-4cf8-97df-a36e1fe905ee)

Let's hope she works 🤞🥰

**Comment by LTVA1** [comment]
@Az-Neter can we discuss the Flizzer tracker stuff somewhere in Discord or similar place? Right now Furnace-B has 8 channels for ATTiny85APU, 3 of them being virtual. Flizzer tracker has hard-coded limit for 4 channels. Also Flizzer tracker does not support Furnace macros. So maybe it would be better to make a standalone player app?

P.S. You can actually run the sound synth routine directly on Flipper

**Comment by Az-Neter** [comment]
> @Az-Neter can we discuss the Flizzer tracker stuff somewhere in Discord or similar place? Right now Furnace-B has 8 channels for ATTiny85APU, 3 of them being virtual. Flizzer tracker has hard-coded limit for 4 channels. Also Flizzer tracker does not support Furnace macros. So maybe it would be better to make a standalone player app?
> 
> P.S. You can actually run the sound synth routine directly on Flipper 

Join Derek Jamison's Flipper Server.
My name in here is Atmatan.

discord.gg/NsjCvqwPAd

**Comment by Az-Neter** [comment]
> Glad it worked! I apologize for not including the fuse info, so here it is:
> The only change to fuse bits needed is to disable `CKDIV8` so that the device runs at a full 8MHz. The rest should stay at their defaults.


For future reference, for anyone else, this requires changing lfuse from 62 to E2 I believe.


You can close this issue, I believe that's all of the problems I've run across so far!
Thanks for all your help. Hopefully this firmware can do what I need it to do. If not, I guess I'm stuck! 😂

**Comment by LTVA1** [comment]
What you want is just a DAC which basically converts input serial data into output PWM. This firmware synthesizes its own sound based on waveform/frequency/volume/etc. data. So you need to write your own simple firmware to do what you need
